---
kind: pipeline
name: default
type: docker

steps:
  - name: rust
    image: rust
    commands:
      - rustup component add rustfmt
      - rustup component add clippy
      - ./.ci/rust.sh
  - name: go
    image: golangci/golangci-lint
    commands:
      - ./.ci/go.sh
