---
kind: pipeline
name: default
type: docker

steps:
  - name: rust
    image: rust
    commands:
      - rustup component add rustfmt
      - rustup component add clippy
      - cd ./rust
      - |
        for prj in */; do
          echo $prj && cd $prj
          cargo fmt
          cargo clippy --all-targets --all-features -- -D warnings
          cd ..
        done
  - name: go
    image: golangci/golangci-lint
    commands:
      - cd ./go
      - |
        for prj in */; do
          echo $prj && cd $prj
          golangci-lint run --enable-all
          cd ..
        done
