---
version: '3'

services:
  karkend:
    image: devopsfaith/krakend
    ports:
      - 8080:8080
    volumes:
      - $PWD/config:/etc/krakend/
    command:
      run --config /etc/krakend/krakend.json
