---
version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: elahe
    ports:
      - 5432:5432
    volumes:
      - ./steps.sql:/docker-entrypoint-initdb.d/steps.sql
