---
version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dvdrental
    ports:
      - 5432:5432
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./procedures.sql:/docker-entrypoint-initdb.d/procedures.sql
      - ./dvdrental.tar:/dvdrental.tar
